name: pangeo
channels:
  - conda-forge
dependencies:
  - python=3.6
  - rasterio
  - numpy
  - scipy
  - pandas
  - xarray
  - matplotlib
  - dask
  - distributed
  - bokeh
  - rasterio
  - geoviews
  - netcdf4
  - zarr
  - lz4
  - nbserverproxy
  - jupyter
  - jupyterlab=0.35
  - ipywidgets
  - ipyleaflet
  - pip:
    - graphviz
    - git+https://github.com/xgcm/xgcm.git
    - git+https://github.com/pydata/xarray.git
    - git+https://github.com/zarr-developers/zarr.git
